---
title: "annotate_cpes"
author: "Humbert Costas"
date: !r Sys.Date()
output: html_document
params:
  seed: 42
  data_path: /DEVEL/code/data/annotation
  path_vers: !r as.character(packageVersion("mitre"))
  output_kind: all
  ner_vendor: FALSE
  ner_product: TRUE
  ner_version: FALSE
  num_samples: 100
---

```{r imports_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Imports
suppressPackageStartupMessages(library(mitre, warn.conflicts = FALSE))
suppressPackageStartupMessages(library(dplyr, warn.conflicts = FALSE))

# Parameters
p_version <- params$path_vers
p_seed <- as.character(params$seed)
p_data_path <- params$data_path
p_num_samples <- params$num_samples   # value 0 means all
p_kind <- params$output_kind         # RASA | entities | all
p_type <- ifelse(test = (params$ner_vendor & params$ner_product & params$ner_version), 
                 yes = "vpv", 
                 no = ifelse(test = (params$ner_vendor & params$ner_product & !params$ner_version), 
                             yes = "vp", 
                             no = ifelse(test = (!params$ner_vendor & params$ner_product & params$ner_version), 
                                         yes = "pv", 
                                         no = ifelse(test = (params$ner_vendor & !params$ner_product & params$ner_version), 
                                                     yes = "vv", 
                                                     no = ifelse(test = (params$ner_vendor), 
                                                                 yes = "vend", 
                                                                 no = ifelse(test = (params$ner_product), 
                                                                             yes = "prod", 
                                                                             no = "vers"))))))

set.seed(p_seed)
```

```{r check_paths}
# root path
if (!dir.exists(p_data_path))
  dir.create(p_data_path)

# version subpath
name_folder <- file.path(p_data_path, paste0("v", p_version))
if (!dir.exists(name_folder))
  dir.create(name_folder)

# seed subpath
name_folder <- file.path(p_data_path, paste0("v", p_version), p_seed)
if (!dir.exists(name_folder))
  dir.create(name_folder)
```

## Annotate CPE standard

```{r get_annotated_cpes}
if (p_kind %in% c("all", "RASA")) {
  # Load CPEs annotated with RASA
  if (file.exists(file.path(name_folder, paste0("cpes_", p_type,"_rasa.rds")))) {
    df_rasa <- readRDS(file.path(name_folder, paste0("cpes_", p_type,"_rasa.rds")))
  } else {
    df_rasa <- mitre::nlp_cpe_annotate(type = p_type, kind = "RASA")
    saveRDS(df_rasa, file.path(name_folder, paste0("cpes_", p_type,"_rasa.rds")))
  }
  readr::write_csv(x = df_rasa,
                   file = file.path(name_folder,paste0("cpes_", p_type,"_rasa.csv")),
                   col_names = FALSE)
}

if (p_kind %in% c("all", "entities")) {
  # Load CPEs annotated with ENTITIES
  if (file.exists(file.path(name_folder, paste0("cpes_", p_type,"_entities.rds")))) {
    df_enti <- readRDS(file.path(name_folder, paste0("cpes_", p_type,"_entities.rds")))
  } else {
    df_enti <- mitre::nlp_cpe_annotate(type = p_type, kind = "entities")
    saveRDS(df_enti, file.path(name_folder, paste0("cpes_", p_type,"_entities.rds")))
  }
  readr::write_csv(x = df_enti,
                   file = file.path(name_folder,paste0("cpes_", p_type,"_entities.csv")),
                   col_names = FALSE)
}
```

## Sampling annotated CPE standard

This sampling version is trying to get observations from different
vendors; to avoid having huge samples of the most common vendors, and ensure 
that contains non common observations.

```{r create_rasa_sample}

if (p_kind %in% c("all", "RASA")) {
  cpes_custom <- nlp.ner_cpe_trainset(kind = "RASA", type = p_type,
                                      num_samples = p_num_samples,
                                      rdataset = file.path(name_folder, paste0("cpes_", p_type,"_rasa.rds")),
                                      seed = p_seed) %>%
    select(title, annotated)
  if (p_num_samples >= 1000) {
    name_file <- file.path(name_folder, paste0("cpes_rasa_", p_type,"_", round(p_num_samples / 1000, 1), "k.csv"))
  } else {
    name_file <- file.path(name_folder,paste0("cpes_rasa_", p_type,"_", p_num_samples, ".csv"))
  }
  readr::write_csv(x = cpes_custom, file = name_file, col_names = FALSE)
}

if (p_kind %in% c("all", "entities")) {
  cpes_custom <- nlp.ner_cpe_trainset(kind = "entities", type = p_type,
                                      num_samples = p_num_samples,
                                      rdataset = file.path(name_folder, paste0("cpes_", p_type,"_entities.rds")),
                                      seed = p_seed) %>%
    select(title, annotated)
  if (p_num_samples >= 1000) {
    name_file <- file.path(name_folder,paste0("cpes_entities_", p_type,"_", round(p_num_samples / 1000, 1), "k.csv"))
  } else {
    name_file <- file.path(name_folder,paste0("cpes_entities_", p_type,"_", p_num_samples, ".csv"))
  }
  readr::write_csv(x = cpes_custom, file = name_file, col_names = FALSE)
}

```

<!-- Let's try another strategy. Now we will select samples using new columns. -->
<!-- First we need to enrich the data. For each column: -->
<!--  - Length: `len_*` -->
<!--  - Number of letters: `abc_*` -->
<!--  - Number of numbers: `num_*` -->
<!--  - Number of symbols: `sym_*` -->

<!-- ```{r feateng} -->
<!-- df <- mitre::nlp_cpe_feateng() -->

<!-- ``` -->

<!-- Now we are ready to explore them with a PCA... -->

<!-- ```{r pca_summary} -->
<!-- pca_cpes <- prcomp(dplyr::select(df, -c("title", "part", "vendor", "product", "version")), scale = T) -->
<!-- summary(pca_cpes) -->

<!-- ``` -->
<!-- The first 7 principal components explains more than 90% of the data variance. -->
<!-- Using the top 10 it almost reach the 99%. -->


<!-- ```{r pca_importance} -->
<!-- PVE <- 100 * pca_cpes$sdev^2 / sum(pca_cpes$sdev^2) -->

<!-- par(mfrow = c(1,2)) -->
<!-- plot(PVE, type = "o", -->
<!--      ylab = "PVE", -->
<!--      xlab = "Componente principal", -->
<!--      col = "blue") -->
<!-- plot(cumsum(PVE), type = "o", -->
<!--      ylab = "PVE acumulada", -->
<!--      xlab = "Componente principal", -->
<!--      col = "brown3") -->
<!-- ``` -->

<!-- ```{r pca_screeplot} -->
<!-- #install.packages("factoextra") -->
<!-- factoextra::fviz_screeplot(pca_cpes, addlabels = TRUE, ylim = c(0, 40)) -->


<!-- ``` -->


<!-- ```{r pca_contribution} -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:10, top = 16) -->

<!-- ``` -->


<!-- ```{r pca_contribution_split} -->
<!-- par(mfrow = c(5,2)) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 2) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 3) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 4) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 5) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 6) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 7) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 8) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 9) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 10) -->


<!-- # for (i in 1:10) { -->
<!-- #   factoextra::fviz_contrib(pca_cpes, choice = "var", axes = i) -->
<!-- # } -->

<!-- ``` -->


<!-- ```{r pca_contribution_split_acum} -->
<!-- par(mfrow = c(5,2)) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:2) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:3) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:4) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:5) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:6) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:7) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:8) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:9) -->
<!-- factoextra::fviz_contrib(pca_cpes, choice = "var", axes = 1:10) -->

<!-- ``` -->

<!-- Let's check the correlation, maybe we can reduce some features... -->

<!-- ```{r plot_correlation} -->
<!-- DataExplorer::plot_correlation(dplyr::select(df, -c("title", "part", "vendor", "product", "version"))) -->

<!-- ``` -->
<!-- We can observe high correlation with length and alphabetic. It seems reasonable  -->
<!-- to keep remove highly correlated features, for example `len_title` and  `sym_title`. -->

<!-- Let's see what happen without them. -->

<!-- ```{r pca_lite_summary} -->
<!-- pca_lite_cpes <- prcomp(dplyr::select(df, -c("title", "part", "vendor", "product",  -->
<!--                                              "version", "len_title", "sym_title")),  -->
<!--                         scale = T) -->
<!-- summary(pca_lite_cpes) -->

<!-- ``` -->
<!-- Minor improvement is noticed. The first 7 PCs explain near 92% and top10 more than 99%. -->

<!-- Let's explore the features... -->

<!-- ```{r pca_lite_importance} -->
<!-- PVE <- 100 * pca_lite_cpes$sdev^2 / sum(pca_lite_cpes$sdev^2) -->

<!-- par(mfrow = c(1,2)) -->
<!-- plot(PVE, type = "o", -->
<!--      ylab = "PVE", -->
<!--      xlab = "Componente principal", -->
<!--      col = "blue") -->
<!-- plot(cumsum(PVE), type = "o", -->
<!--      ylab = "PVE acumulada", -->
<!--      xlab = "Componente principal", -->
<!--      col = "brown3") -->
<!-- ``` -->

<!-- ```{r pca_lite_contribution} -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 1:7) -->

<!-- ``` -->

<!-- ```{r pca_lite_contribution_split} -->
<!-- par(mfrow = c(5,2)) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 1) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 2) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 3) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 4) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 5) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 6) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 7) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 8) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 9) -->
<!-- factoextra::fviz_contrib(pca_lite_cpes, choice = "var", axes = 10) -->

<!-- ``` -->

<!-- ~~Maybe is better to keep title length feature and remove the other lengths.~~ -->

<!-- After playing with features... -->

<!-- ```{r pca_lite2_summary} -->
<!-- pca_lite2_cpes <- prcomp(dplyr::select(df, -c("title", "part", "vendor", "product", "version",  -->
<!--                                               # "len_title",  -->
<!--                                               "len_vendor", "len_product", "len_version", -->
<!--                                               "sym_title",  -->
<!--                                               "num_title", -->
<!--                                               "abc_title", -->
<!--                                               # "abc_vendor", "abc_product", "num_version" -->
<!--                                               )),  -->
<!--                         scale = T) -->
<!-- summary(pca_lite2_cpes) -->

<!-- ``` -->
<!-- ```{r pca_lite2_importance} -->
<!-- PVE2 <- 100 * pca_lite2_cpes$sdev^2 / sum(pca_lite2_cpes$sdev^2) -->

<!-- par(mfrow = c(1,2)) -->
<!-- plot(PVE2, type = "o", -->
<!--      ylab = "PVE2", -->
<!--      xlab = "Componente principal", -->
<!--      col = "blue") -->
<!-- plot(cumsum(PVE2), type = "o", -->
<!--      ylab = "PVE2 acumulada", -->
<!--      xlab = "Componente principal", -->
<!--      col = "brown3") -->
<!-- ``` -->

<!-- ```{r pca_lite2_contribution} -->
<!-- factoextra::fviz_contrib(pca_lite2_cpes, choice = "var", axes = 1:7) -->

<!-- ``` -->

<!-- ```{r plot_correlation_lite2} -->
<!-- DataExplorer::plot_correlation(dplyr::select(df, c("num_vendor", "sym_vendor", "abc_version",   -->
<!--                                                    "sym_version", "abc_vendor", "sym_product"))) -->

<!-- ``` -->

