---
title: "MITRE graph analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MITRE_graph_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mitre)
suppressPackageStartupMessages(library(igraph))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(kableExtra))
```

# MITRE graph

```{r load_data, cache=TRUE}
# mitredata <- mitre::getLatestDataSet()
mitredata <- readRDS("C:/DEVEL/datasets/mitre-datasets/latest/mitre_latest.rds")
migraph <- mitre::as_igraph(mitredata$mitrenet)
```

```{r basic_stats}
kbl(as.data.frame(table(standard = V(migraph)$group), 
                  stringsAsFactors = F, responseName = "count")) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

Let's start checking threats with active groups.

```{r threat_start}
th.group <- mitredata$standards$attck$groups
selnodes <- V(migraph)$group == "attck-group"
```
1. How many connections has each node?
```{r threat_stats_1}
barplot(sort(degree(migraph, selnodes, mode="all"), T))
```

2. Which are deprecated/revoked?
```{r threat_stats_2}
selnodes <- V(migraph)$name %in%
  (th.group %>% 
     top_n(n = 3, wt = modified) %>% 
     select(mitreid))$mitreid
ig.topg <- ego(migraph, order = 1, nodes = selnodes, mode = "all", mindist = 0)
ig.topg <- induced_subgraph(migraph, unlist(ig.topg))
```

3. Which are the most recent (last 6 months) created/modified?
```{r threat_stats_3}
selnodes <- V(migraph)$name %in% th.group[th.group$modified > (Sys.time() - 3600*24*185), "mitreid"]
barplot(sort(degree(migraph, selnodes, mode="all"), T))

```




